
#Person Info through another proeprties


person.info.personId=23455
person.info.personName=Parag 
person.info.mobileNumber=8924897
person.info.personSalary=6348.4732
person.info.personAddress=Mumbai



