spring.application.name=ConfigurationProperties-Bulk_Injection-2


# initializing the person details

person.info.personId=12345
person.info.personName=Atharv 
#person.info.mobileNumber=789489348
#person.info.personSalary=6348.4732
#person.info.personAddress="kolhapur
#

#Comfiguring the user defined properties file 

spring.config.import=com/nt/config/Hello.properties